name: Build Native Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [windows-latest, ubuntu-latest, macos-latest]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Act dependencies
        if: ${{ env.ACT && matrix.os == 'ubuntu-latest' }}
        run: |
          apt-get update && apt-get install sudo curl wget build-essential ninja-build git -y

      - name: Set up Python and pip
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install python3 python3-pip -y

      - name: Set up Python and pip
        if: matrix.os == 'windows-latest'
        run: |
          choco install python --version=3.9
          refreshenv
          python -m ensurepip
          python -m pip install --upgrade pip

      - name: Set up Python and pip (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install python
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip

      - name: Set up CMake
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Remove existing CMake if it's too old
          sudo apt-get remove -y cmake

          # Detect architecture (x86_64 or aarch64)
          ARCH=$(uname -m)
          CMAKE_VERSION="3.25.0"  # Specify the version you need (>= 3.15)

          if [[ "$ARCH" == "x86_64" ]]; then
            echo "Detected x86_64 architecture"
            CMAKE_ARCH="linux-x86_64"
          elif [[ "$ARCH" == "aarch64" ]]; then
            echo "Detected ARM architecture (aarch64)"
            CMAKE_ARCH="linux-aarch64"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi

          # Download the correct CMake binary
          wget https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-$CMAKE_ARCH.tar.gz

          # Extract the tarball
          tar -xzf cmake-$CMAKE_VERSION-$CMAKE_ARCH.tar.gz

          # Install CMake to /usr/local without overwriting existing directories
          echo "Installing CMake to /usr/local..."
          sudo cp -r cmake-$CMAKE_VERSION-$CMAKE_ARCH/bin /usr/local/
          sudo cp -r cmake-$CMAKE_VERSION-$CMAKE_ARCH/share /usr/local/

          # Clean up
          rm -rf cmake-$CMAKE_VERSION-$CMAKE_ARCH.tar.gz cmake-$CMAKE_VERSION-$CMAKE_ARCH

          # Verify CMake installation
          cmake --version

      - name: Set up CMake
        if: matrix.os == 'windows-latest'
        run: choco install cmake

      - name: Set up CMake
        if: matrix.os == 'macos-latest'
        run: brew install cmake

      - name: Set up Conan
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            source venv/bin/activate
          fi

          # Install Conan in the virtual environment
          python3 -m pip install conan

          # Verify Conan installation
          conan --version

      - name: Set up Emscripten (for WebAssembly)
        if: matrix.os == 'ubuntu-latest'  # Only run on Linux for WebAssembly
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - name: Build plugin
        run: |
          mkdir build
          cd build

          # Re-activate the virtual environment (macOS-specific)
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            source ../venv/bin/activate
          fi

          conan profile detect --force

          # Use the appropriate Conan profile for the platform
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            ARCH=$(uname -m)
            if [[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]]; then
              echo "Detected ARM Linux (aarch64/arm64)"
              conan install .. --profile=../conan/linux_arm.profile --build=missing
            elif [[ "$ARCH" == "x86_64" ]]; then
              echo "Detected x86_64 Linux"
              conan install .. --profile=../conan/linux_x86_64.profile --build=missing
            else
              echo "Unsupported architecture: $ARCH"
              exit 1
            fi
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            conan install .. --profile=../conan/windows.profile --build=missing
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Detect architecture (x86_64 or arm64)
            ARCH=$(uname -m)
            if [[ "$ARCH" == "arm64" ]]; then
              echo "Detected Apple Silicon (arm64)"
              conan install .. --profile=../conan/macos.profile -s arch=armv8 --build=missing
            else
              echo "Detected Intel (x86_64)"
              conan install .. --profile=../conan/macos.profile -s arch=x86_64 --build=missing
            fi
          fi

          # Configure CMake with the Conan toolchain
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake

          # Build the project
          cmake --build .
          cpack .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !env.ACT }}
        with:
          name: my_plugin_${{ matrix.os }}
          path: build/**.zip

      - name: Save artifacts
        if: ${{ env.ACT }}
        run: |
          mkdir -p artifacts
          cp -r build/ artifacts/
          ls -la artifacts